# Generated by Django 5.2 on 2025-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
