# Generated by Django 5.2 on 2025-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woox', '0002_destination_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='population',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='territory',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
