# Generated by Django 5.2 on 2025-04-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woox', '0003_destination_population_destination_territory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='destination',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
